apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: student-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: student-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
