#2
apiVersion: v1
kind: Service
metadata:
  name: student-appservice
spec:
  selector:
    app: student-app
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    # - name: tcp
    #   port: 8080
    #   protocol: TCP
    - name: tcp
      port: 8080
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer