version: "3"
services:
  fluentd:
    build: .
    volumes:
      - ./conf:/fluentd/etc
    # links:
    #   - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
  #   container_name: elasticsearch
  #   environment:
  #     - "discovery.type=single-node"
  #   expose:
  #     - "9200"
  #   ports:
  #     - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.3.3
  #   container_name: kibana
  #   links:
  #     - "elasticsearch"
  #   ports:
  #     - "5601:5601"